# Generated by Django 4.1.1 on 2025-02-04 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratorio', '0002_actualizado_campos'),
    ]

    operations = [
        migrations.AddField(
            model_name='laboratorio',
            name='direccion',
            field=models.CharField(default='No especificado', max_length=255),
        ),
        migrations.AddField(
            model_name='laboratorio',
            name='telefono',
            field=models.CharField(default='No especificado', max_length=20),
        ),
    ]
